apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: igbe5r87z-go 
  janus-idp.io/tekton: igbe5r87z-go
  backstage.io/kubernetes-id: igbe5r87z-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: igbe5r87z-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  